[package]
name = "jolly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {git = "https://github.com/iced-rs/iced.git", rev = "aeec037"}
iced_native = {git = "https://github.com/iced-rs/iced.git", rev = "aeec037"}
toml = { version = "0.5.8", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
dirs = "4"
blocking = "1"
opener = "0.5.0"
urlencoding = "2.1.0"

[dev-dependencies] 
tempfile = "3"

[target.'cfg(windows)'.build-dependencies]
resvg = "0.20.0"
usvg = "0.20.0"
tiny-skia = "0.6.1"
ico = "0.1.0"
winres = "0.1.12"

