[package]
name = "jolly"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {git = "https://github.com/iced-rs/iced.git"}
iced_native = {git = "https://github.com/iced-rs/iced.git"}
toml = { version = "0.5.8", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
dirs = "4"

[dev-dependencies] 
tempfile = "3"
