[package]
name = "jolly"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "small bookmarking launcher for desktop usage, developed with iced"
homepage = "https://github.com/apgoetz/jolly"
documentation = "https://github.com/apgoetz/jolly"
repository = "https://github.com/apgoetz/jolly"
readme = "README.md"
keywords = ["launcher","bookmarks", "iced"]
exclude = ["docs/"]

[dependencies]
iced = "0.6.0"
iced_native = "0.7.0"
toml = { version = "0.5.8", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
dirs = "4"
blocking = "1"
opener = "0.5.0"
urlencoding = "2.1.0"
lazy_static = "1"

[dev-dependencies] 
tempfile = "3"

[target.'cfg(windows)'.build-dependencies]
resvg = "0.28.0"
usvg = "0.28.0"
tiny-skia = "0.8.2"
ico = "0.2.0"
winres = "0.1.12"

[target.'cfg(windows)'.dependencies.windows]
version = "0.43.0"
features = [
	 'UI_ViewManagement'
]
