# use your system's default program to open this jolly database
['Edit Jolly Configuration']
location = 'jolly.toml'


['Jolly Homepage']
location = 'https://github.com/apgoetz/jolly'
tags = ['docs','jolly']


['Search DuckDuckGo: %s']
location = 'https://duckduckgo.com/?q=%s'
keyword = 'ddg'
escape = true

['Complain to Jolly Developers']
location = 'mailto:example@example.com'

# open your system's calculator app. This example uses the Windows
# calculator app, but for other operating systems you may need to
# replace the program. For example, on Debian, you can use
# 'gnome-calculator' and on MacOs you can use
# '/System/Applications/Calculator.app/Contents/MacOS/Calculator'
['Open Calculator']
system = 'calc.exe'
tags = ['math', 'work']
